### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by ethanmick** [fastchat/server#101]
Make it super easy to deploy for new users.

**Comment by del6597** [comment]
A package for a client? A server? Both?

**Comment by ethanmick** [comment]
Server, since client is built in to server currently.

Something like, `npm install fastchat-server -g`

And then you could go to localhost and it would be there.

**Comment by ethanmick** [comment]
Blocked by #118, #119, #120.

**Comment by ethanmick** [comment]
Unblocked.

**Comment by ethanmick** [comment]
Live now!
